/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package airlineReservation;

/**
 * This class creates the 2nd JFrame that pops up as a boarding pass or receipt.
 * @author Mike Plucker, Billy Lam, Xavier Porter
 * Class: CSCI 2001-51
 * Due Date: 03/31/14
 * 
 * Version 1.00
 * 
 * 
 */

public class AirlineReciept extends javax.swing.JFrame {
    
    
    /**
     * Creates new form AirlineReciept
     * @param firstName
     * @param seat
     * @param lastName
     */
    public AirlineReciept(String firstName, String lastName, String seat) {
        initComponents();
        
        firstNameLabel.setText(firstName);
        lastNameLabel.setText(lastName);
        seatLabel.setText(seat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        seatLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setTitle("Boarding Pass");
        setMinimumSize(new java.awt.Dimension(336, 284));
        getContentPane().setLayout(null);

        firstNameLabel.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        getContentPane().add(firstNameLabel);
        firstNameLabel.setBounds(122, 46, 82, 38);

        lastNameLabel.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        getContentPane().add(lastNameLabel);
        lastNameLabel.setBounds(206, 44, 106, 40);

        seatLabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        getContentPane().add(seatLabel);
        seatLabel.setBounds(16, 90, 288, 34);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlineReservation/images/BoardingPass2.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, -28, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AirlineReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AirlineReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AirlineReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirlineReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AirlineReciept().setVisible(true);   
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel seatLabel;
    // End of variables declaration//GEN-END:variables
}
