
package airlineReservation;

/**
 * @author: Mike Plucker, Billy Lam, Xavier Porter
 * Class: CSCI 2001-51
 * Due Date: 03/31/14
 * 
 * Version: 1.00
 * 
 * 
 * Generates the GUI for the MathGame
 */


//import classes
import java.io.*;


public class AirlineReservationGUI extends javax.swing.JFrame {
    
    //create AirlineReservation object
    AirlineReservation airline = new AirlineReservation();
    

    /**
     * Creates new form AirlineReservationGUI
     */
    public AirlineReservationGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    
   
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton23 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();
        jToggleButton25 = new javax.swing.JToggleButton();
        jToggleButton26 = new javax.swing.JToggleButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vay Cay Shun Airlines");
        setMaximumSize(new java.awt.Dimension(670, 656));
        setMinimumSize(new java.awt.Dimension(670, 656));
        getContentPane().setLayout(null);

        jToggleButton1.setText("1 C");
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(458, 444, 48, 48);

        jToggleButton5.setText("1 A");
        getContentPane().add(jToggleButton5);
        jToggleButton5.setBounds(316, 444, 48, 48);

        jToggleButton6.setText("1 D");
        getContentPane().add(jToggleButton6);
        jToggleButton6.setBounds(506, 444, 48, 48);

        jToggleButton7.setText("2 A");
        getContentPane().add(jToggleButton7);
        jToggleButton7.setBounds(316, 394, 48, 48);

        jToggleButton8.setText("2 B");
        getContentPane().add(jToggleButton8);
        jToggleButton8.setBounds(366, 394, 48, 48);

        jToggleButton9.setText("2 C");
        getContentPane().add(jToggleButton9);
        jToggleButton9.setBounds(458, 394, 48, 48);

        jToggleButton10.setText("2 D");
        getContentPane().add(jToggleButton10);
        jToggleButton10.setBounds(506, 394, 48, 48);

        jToggleButton11.setText("1 B");
        getContentPane().add(jToggleButton11);
        jToggleButton11.setBounds(366, 444, 48, 48);

        jToggleButton2.setText("jToggleButton2");
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(348, 320, 36, 38);

        jToggleButton3.setText("jToggleButton2");
        getContentPane().add(jToggleButton3);
        jToggleButton3.setBounds(384, 320, 36, 38);

        jToggleButton4.setText("jToggleButton2");
        getContentPane().add(jToggleButton4);
        jToggleButton4.setBounds(450, 320, 36, 36);

        jToggleButton12.setText("jToggleButton2");
        getContentPane().add(jToggleButton12);
        jToggleButton12.setBounds(486, 320, 36, 36);

        jToggleButton13.setText("jToggleButton2");
        getContentPane().add(jToggleButton13);
        jToggleButton13.setBounds(522, 320, 36, 36);

        jToggleButton14.setText("jToggleButton2");
        getContentPane().add(jToggleButton14);
        jToggleButton14.setBounds(312, 286, 36, 36);

        jToggleButton15.setText("jToggleButton2");
        getContentPane().add(jToggleButton15);
        jToggleButton15.setBounds(348, 286, 36, 36);

        jToggleButton16.setText("jToggleButton2");
        getContentPane().add(jToggleButton16);
        jToggleButton16.setBounds(384, 286, 36, 36);

        jToggleButton17.setText("jToggleButton2");
        getContentPane().add(jToggleButton17);
        jToggleButton17.setBounds(450, 284, 36, 36);

        jToggleButton18.setText("jToggleButton2");
        getContentPane().add(jToggleButton18);
        jToggleButton18.setBounds(486, 284, 36, 36);

        jToggleButton19.setText("jToggleButton2");
        getContentPane().add(jToggleButton19);
        jToggleButton19.setBounds(522, 284, 36, 36);

        jToggleButton20.setText("jToggleButton2");
        getContentPane().add(jToggleButton20);
        jToggleButton20.setBounds(312, 250, 36, 36);

        jToggleButton21.setText("jToggleButton2");
        getContentPane().add(jToggleButton21);
        jToggleButton21.setBounds(348, 250, 36, 36);

        jToggleButton22.setText("jToggleButton2");
        getContentPane().add(jToggleButton22);
        jToggleButton22.setBounds(384, 250, 36, 36);

        jToggleButton23.setText("jToggleButton2");
        getContentPane().add(jToggleButton23);
        jToggleButton23.setBounds(450, 250, 36, 36);

        jToggleButton24.setText("jToggleButton2");
        getContentPane().add(jToggleButton24);
        jToggleButton24.setBounds(486, 250, 36, 36);

        jToggleButton25.setText("jToggleButton2");
        getContentPane().add(jToggleButton25);
        jToggleButton25.setBounds(522, 250, 36, 36);

        jToggleButton26.setText("jToggleButton2");
        getContentPane().add(jToggleButton26);
        jToggleButton26.setBounds(312, 321, 36, 36);

        background.setBackground(new java.awt.Color(153, 255, 153));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageDisplay/Airline 14.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, -50, 740, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AirlineReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AirlineReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AirlineReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirlineReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AirlineReservationGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton26;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}
